name: Kernel Image.gz Only Build (With kernel_src)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache flex \
            git libssl-dev python3 rsync unzip zip zlib1g-dev \
            libncurses5-dev libelf-dev lz4 device-tree-compiler curl

      - name: Install Repo Tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Init Repo & Add Local Manifest (Prebuilts Only)
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://github.com/darklord4567/Sukisu_nord4 -m default.mxl --depth=1


      - name: Sync AOSP Prebuilts
        run: |
          cd kernel_workspace
          repo sync -c --no-tags --no-clone-bundle --force-sync -j$(nproc --all)

      - name: Clone OnePlus Kernel Source (to kernel_src)
        run: |
          cd kernel_workspace
          git clone https://github.com/stuffbykoko/kernel_oneplus_sm8650.git -b lineage-22.2 kernel_src
      
      - name: Build Kernel (Image.gz Only)
        run: |
          cd kernel_workspace/kernel_src
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export LOCALVERSION="-custom"
          export CLANG_PATH=$GITHUB_WORKSPACE/kernel_workspace/prebuilts-master/clang/host/linux-x86/clang-r487747c/bin
          export GCC_PATH=$GITHUB_WORKSPACE/kernel_workspace/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-gnu/bin
          export PATH=$CLANG_PATH:$GCC_PATH:/usr/lib/ccache:$PATH
          export CC="ccache clang"
      
          make O=out gki_defconfig
          make O=out -j$(nproc --all) Image.gz



      - name: Upload Built Image.gz
        uses: actions/upload-artifact@v4
        with:
          name: Built-Image.gz
          path: kernel_workspace/kernel_src/out/arch/arm64/boot/Image.gz
