name: Kernel Image.gz Only Build (With kernel_src)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache flex \
            git libssl-dev python3 rsync unzip zip zlib1g-dev \
            libncurses5-dev libelf-dev lz4 device-tree-compiler curl

      - name: Install Repo Tool
        run: |
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
          chmod a+x ~/repo
          sudo mv ~/repo /usr/local/bin/repo

      - name: Init Repo & Add Local Manifest (AOSP Prebuilts Only)
        run: |
          mkdir kernel_workspace && cd kernel_workspace
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android14-6.1 --depth=1
          
          mkdir -p .repo/local_manifests
          cat <<EOF > .repo/local_manifests/local_manifest.xml
          <?xml version="1.0" encoding="UTF-8"?>
          <manifest>
            <default revision="common-android14-6.1" remote="aosp" sync-j="4" />
            <project path="build" name="kernel/build" />
            <project path="kernel/tests" name="kernel/tests" />
            <project path="kernel/configs" name="kernel/configs" />
            <project path="prebuilts/build-tools" name="platform/prebuilts/build-tools" clone-depth="1" />
            <project path="prebuilts/kernel-build-tools" name="kernel/prebuilts/build-tools" clone-depth="1" />
            <project path="prebuilts-master/clang/host/linux-x86" name="platform/prebuilts/clang/host/linux-x86" clone-depth="1" />
            <project path="prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8" name="platform/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8" clone-depth="1" />
          </manifest>
          EOF

      - name: Sync AOSP Prebuilts
        run: |
          cd kernel_workspace
          repo sync -c --no-tags --no-clone-bundle --force-sync -j$(nproc --all)

      - name: Clone OnePlus Kernel Source (to kernel_src)
        run: |
          cd kernel_workspace
          git clone https://github.com/stuffbykoko/kernel_oneplus_sm8650.git -b lineage-22.2 kernel_src

      - name: Build Kernel (Image.gz Only)
        run: |
          cd kernel_workspace/kernel_src
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=aarch64-linux-gnu-
          export LOCALVERSION="-custom"
          export PATH=$GITHUB_WORKSPACE/kernel_workspace/prebuilts-master/clang/host/linux-x86/clang-r487747c/bin:$PATH
          export PATH="/usr/lib/ccache:$PATH"
          export CC="ccache clang"

          make O=out gki_defconfig
          make O=out -j$(nproc --all) Image.gz

      - name: Upload Built Image.gz
        uses: actions/upload-artifact@v4
        with:
          name: Built-Image.gz
          path: kernel_workspace/kernel_src/out/arch/arm64/boot/Image.gz
