# .github/workflows/release-kernel.yml

name: Create Kernel Release

on:
  workflow_dispatch:
    inputs:
      run_url:
        description: 'Paste the full URL of the successful build run'
        required: true
      device_name:
        description: 'Device name for the release (e.g., oneplus_nord_4_v)'
        required: true
        default: 'oneplus_nord_4_v'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    env:
      TZ: Asia/Kolkata
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Extract Run ID from URL
        run: |
          RUN_ID=$(basename "${{ inputs.run_url }}")
          echo "Extracted Run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Generate IST Release Tag
        run: |
          TAG="${{ inputs.device_name}}-$(date +'%Y-%m-%d_%H-%M')-IST"
          echo "Generated Tag: $TAG"
          # ==> FIX: This sets the variable 'tag', which we will use below
          echo "tag=$TAG" >> $GITHUB_ENV

      # ==> FIX: Using the correct action to download from a *different* workflow run
      - name: Download Build Artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-kernel.yml # The filename of your build workflow
          # ==> FIX: Using the 'RUN_ID' variable extracted from the URL
          run_id: ${{ env.RUN_ID }}
          path: ./downloaded-artifacts
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # ==> FIX: Corrected 'tag_name' and 'body' formatting
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.tag }}
          release_name: "Kernel Release for ${{ inputs.device_name }} - $(date +'%d %B %Y, %I:%M %p IST')"
          body: |
            ### SukiSU Ultra Kernel for ${{ inputs.device_name }}

            **Flasher Recommendation:**
            -> [Kernel Flasher](https://github.com/fatalcoder524/KernelFlasher)

            **Manager App:**
            -> [SukiSU-Ultra Manager](https://github.com/SukiSU-Ultra/SukiSU-Ultra/releases/latest)

      # ==> FIX: Using the correct tag variable and a better loop
      - name: Upload Release Assets
        run: |
          find ./downloaded-artifacts -type f | while read -r file; do
            echo "Uploading $file..."
            gh release upload "${{ env.tag }}" "$file"
          done
