# .github/workflows/release-kernel.yml

name: Create Kernel Release

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The ID of the successful build run to release from'
        required: true
      device_name:
        description: 'Device name for the release (e.g., oneplus_nord_4_v)'
        required: true
        default: 'oneplus_nord_4_v'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    env:
      TZ: Asia/Kolkata
      # Set the token once for all steps in the job
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate IST Release Tag
        run: |
          TAG="${{ inputs.device_name}}-$(date +'%Y-%m-%d_%H-%M')-IST"
          echo "Generated Tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Download Artifacts via GitHub CLI
        run: |
          echo "Downloading artifacts for Run ID ${{ inputs.run_id }}..."
          gh run download ${{ inputs.run_id }} --dir ./downloaded-artifacts --repo ${{ github.repository }}

      - name: Display Downloaded Artifact Structure
        run: ls -R ./downloaded-artifacts

      - name: Zip Each Artifact Individually
        run: |
          mkdir ./final-zips
          for dir in ./downloaded-artifacts/*; do
            if [ -d "$dir" ]; then
              ARTIFACT_NAME=$(basename "$dir")
              echo "Zipping artifact: $ARTIFACT_NAME"
              (cd "$dir" && zip -r9 "$GITHUB_WORKSPACE/final-zips/${ARTIFACT_NAME}.zip" .)
            fi
          done

      - name: Display Final Zip Files
        run: ls -l ./final-zips

      - name: Create GitHub Release and Upload Zips
        env:
          RELEASE_NOTES: |
            ### SukiSU Ultra Kernel for ${{ inputs.device_name }}
            Flash the appropriate zip file below using a custom recovery.
            
            **Flasher Recommendation:**
            -> [Kernel Flasher](https://github.com/fatalcoder524/KernelFlasher)
            
            **Manager App:**
            -> [SukiSU-Ultra Manager](https://github.com/SukiSU-Ultra/SukiSU-Ultra/releases/latest)
        run: |
          gh release create "${{ env.tag }}" \
            --title "Kernel Release for ${{ inputs.device_name }} - $(date +'%d %B %Y, %I:%M %p IST')" \
            --notes "$RELEASE_NOTES" \
            ./final-zips/*.zip
