# .github/workflows/release-kernel.yml

name: Create Kernel Release

on:
  workflow_dispatch:
    inputs:
      # This input now accepts the full URL
      run_url:
        description: 'Paste the full URL of the successful build run'
        required: true
      device_name:
        description: 'Device name for the release (e.g., oneplus_nord_4_v)'
        required: true
        default: 'oneplus_nord_4_v'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    env:
      TZ: Asia/Kolkata

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # ==> NEW STEP: Extracts the ID from the URL <==
      - name: Extract Run ID from URL
        run: |
          # Takes the last part of the URL, which is the Run ID
          RUN_ID=$(basename "${{ inputs.run_url }}")
          echo "Extracted Run ID: $RUN_ID"
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      # This step now uses the extracted ID
      - name: Download All Build Artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build-kernel.yml
          run_id: ${{ env.RUN_ID }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: ./downloaded-artifacts

      - name: Display Downloaded Artifact Structure
        run: ls -R ./downloaded-artifacts

      - name: Zip Each Artifact Individually
        run: |
          mkdir ./final-zips
          for dir in ./downloaded-artifacts/*; do
            if [ -d "$dir" ]; then
              ARTIFACT_NAME=$(basename "$dir")
              echo "Zipping artifact: $ARTIFACT_NAME"
              (cd "$dir" && zip -r9 "$GITHUB_WORKSPACE/final-zips/${ARTIFACT_NAME}.zip" .)
            fi
          done

      - name: Display Final Zip Files
        run: ls -l ./final-zips

      - name: Generate IST Release Tag
        run: |
          TAG="${{ inputs.device_name}}-$(date +'%Y-%m-%d_%H-%M')-IST"
          echo "Generated Tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV
      
      - name: Create GitHub Release and Upload Zips
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: |
            ### SukiSU Ultra Kernel for ${{ inputs.device_name }}
            Flash the appropriate zip file below using a custom recovery.
            
            **Flasher Recommendation:**
            -> [Kernel Flasher](https://github.com/fatalcoder524/KernelFlasher)

            **Manager App:**
            -> [SukiSU-Ultra Manager](https://github.com/SukiSU-Ultra/SukiSU-Ultra/releases/latest)
        run: |
          gh release create "${{ env.tag }}" \
            --title "Kernel Release for ${{ inputs.device_name }} - $(date +'%d %B %Y, %I:%M %p IST')" \
            --notes "$RELEASE_NOTES" \
            ./final-zips/*.zip
