# .github/workflows/release-kernel.yml

name: Create Kernel Release

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The ID of the successful build run to release from'
        required: true
      device_name:
        description: 'Device name for the release (e.g., oneplus_nord_4_v)'
        required: true
        default: 'oneplus_nord_4_v'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # To create tags and releases
      actions: read   # To download artifacts from other workflows
    env:
      TZ: Asia/Kolkata

    steps:
      - name: Download Artifacts from Build Workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          # The name of the build workflow file
          workflow: build-kernel.yml
          # The specific run ID you provided as input
          run_id: ${{ inputs.run_id }}
          # The token is required to access artifacts from other workflow runs
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Download all artifacts from that run
          # They will be placed in directories named after the artifact
          path: ./release-artifacts
      
      - name: Display Downloaded Files
        run: ls -R ./release-artifacts

      - name: Generate IST Release Tag
        run: |
          TAG="${{ inputs.device_name }}-$(date +'%Y%m%d-%H%M')-IST"
          echo "Generated Tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: |
            ### SukiSU Ultra Kernel for ${{ inputs.device_name }}
            This release contains SukiSU supported Kernel for OnePlus Nord 4.

            **Flasher Recommendation:**
            -> [Kernel Flasher](https://github.com/fatalcoder524/KernelFlasher)

            **Required Modules:**
            -> [Susfs Module](https://github.com/sidex15/susfs4ksu-module)

            **Manager App:**
            -> [SukiSU-Ultra Manager](https://github.com/SukiSU-Ultra/SukiSU-Ultra/releases/latest)

        run: |
          # Use find to locate all files within the downloaded artifact directories
          gh release create "${{ env.tag }}" \
            --title "Kernel Release for ${{ inputs.device_name }} - $(date +'%d %B %Y, %I:%M %p IST')" \
            --notes "$RELEASE_NOTES" \
            $(find ./release-artifacts -type f)
