name: Create Kernel Release

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'The ID of the successful build run to release from'
        required: true
      device_name:
        description: 'Device name for the release (e.g., oneplus_nord_4_v)'
        required: true
        default: 'oneplus_nord_4_v'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    env:
      TZ: Asia/Kolkata

    steps:
      - name: Download Build Artifacts
        uses: dawidd6/action-download-artifact@v6
        with:
          # The name of the build workflow file
          workflow: Fast_SukiSU_build_n4.yml
          run_id: ${{ inputs.run_id }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The action will download all artifacts from that run
          path: ./release-artifacts

      - name: Display Downloaded Files
        run: ls -R ./release-artifacts

      - name: Generate IST Release Tag
        run: |
          TAG="${{ inputs.device_name }}-$(date +'%Y%m%d-%H%M')-IST"
          echo "Generated Tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_ENV

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NOTES: |
            ### SukiSU Ultra Kernel for ${{ inputs.device_name }}
            This release was generated on **${{ fromJson(steps.get_time.outputs.json).date }}**.

            **Flasher Recommendation:**
            -> [Kernel Flasher](https://github.com/fatalcoder524/KernelFlasher)

            **Manager App:**
            -> [SukiSU-Ultra Manager](https://github.com/SukiSU-Ultra/SukiSU-Ultra/releases/latest)

        run: |
          # The find command reliably uploads all files from all downloaded artifact folders
          gh release create "${{ env.tag }}" \
            --title "Kernel Release for ${{ inputs.device_name }} - $(date +'%d %B %Y, %I:%M %p IST')" \
            --notes "$RELEASE_NOTES" \
            $(find ./release-artifacts -type f)
